## Customize the test machine
machine:

  timezone:
    Japan/Tokyo # Set the timezone

  # Version of ruby to use
  java:
    version: openjdk8

  # Override /etc/hosts
  hosts:
    circlehost: 127.0.0.1
    dev.mycompany.com: 127.0.0.1

  # Add some environment variables
  environment:
    CIRCLE_ENV: test
    # DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
    
    services:
        - cassandra
## servicesはCircleCiがデフォルトでインストールしていないdb serviceをインストールしたい時に記述

## Customize checkout
# checkout:
#  post:
 #   - git submodule sync
 #   - git submodule update --init # use submodules
## checkoutはgitのsubmoduleを追加する時などに記述

## Customize dependencies
dependencies:
  pre: ## CircleCiのデフォルトコマンド実行前
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
   
  override: ## デフォルトのコマンドを上書き
    - bundle install: # note ':' here
        timeout: 180 # fail if command has no output for 3 minutes
        # IMPORTANT NOTE: ^^ the timeout modifier above must be
        # double indented (four spaces) from the previous line
  
  # we automatically cache and restore many dependencies between
  # builds. If you need to, you can add custom paths to cache:
  cache_directories:
    - "custom_1"   # relative to the build directory
    - "~/custom_2" # relative to the user's home directory

## Customize database setup
database:
  override:
    - mysql -u ubuntu circle_test < my-database-setup.sql
    ## sampleやテストデータなどをsql等でinsertしたい場合に使う

## Customize test commands
test:
#  override:
 #   - phpunit test/unit-tests # use PHPunit for testing
  post: ## CircleCiの実行後デフォルトコマンド
    - mvn package

## Customize deployment commands
deployment:
  staging:
    branch: master
    heroku:
      appname: foo-bar-123

## Custom notifications
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://someurl.com/hooks/circle
