## Customize the test machine
machine:

  timezone:
    asia/Tokyo # Set the timezone

  # Version of ruby to use
  java:
    version: openjdk8

  # Override /etc/hosts
  hosts:
    circlehost: 127.0.0.1
    dev.mycompany.com: 127.0.0.1

