language : java
before_install:
 - sudo apt-get update
 - sudo apt-get install oracle-java8-installer
jdk : 
 - oraclejdk8

services:
  - mysql
 
cache:
 directories:
 - .autoconf
 - $HOME/.m2

notifications:
  email:
    - kkkiyuu911111@yahoo.co.jp

sudo: required
services:
- docke

branches:
  except:
    - master
